Don't attach images to DOM if logos are missing
ChartIQ/finsemble-notifications pull request #94
Opened 2020-12-07 16:51 UTC by clausjs

- Adds React changes to avoid attaching <img> to DOM when `contentLogo` or `headerLogo` are undefined for a notification

2020-12-07 17:14 UTC, gerard-ciq commented on components/shared/components/Notification.tsx
> +	console.log("notification: ", notification);
```suggestion
```

2020-12-07 17:15 UTC, gerard-ciq requested changes
remove console.log otherwise lgtm

2020-12-08 14:06 UTC, sgd2z approved these changes

2020-12-08 16:08 UTC, gerard-ciq approved these changes

2020-12-08 16:34 UTC, merged